const icon=(type)=>{const p={design:'<path d="M4 20 20 4l2 2L6 22l-3 1zM14 5l5 5M4 14l5 5"/>',ux:'<rect x="4" y="3" width="16" height="18" rx="2"/><path d="M8 7h8M8 11h5M8 16h8"/>',social:'<path d="M5 18v-5M10 18V9M15 18v-8M20 18V5"/><path d="M4 21h17"/>',ai:'<rect x="7" y="7" width="10" height="10" rx="2"/><path d="M10 1v3M14 1v3M10 20v3M14 20v3M1 10h3M1 14h3M20 10h3M20 14h3M10 11h.01M14 11h.01M12 14h.01"/>',code:'<path d="m8 8-4 4 4 4M16 8l4 4-4 4M14 4l-4 16"/>',write:'<path d="M4 20h4l11-11a2.8 2.8 0 0 0-4-4L4 16zM13 6l5 5"/>',video:'<rect x="3" y="6" width="13" height="12" rx="2"/><path d="m16 10 5-3v10l-5-3z"/>',marketing:'<path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/>',search:'<circle cx="11" cy="11" r="6"/><path d="m20 20-4-4"/>',data:'<path d="M4 20V4M4 20h17M8 16l4-5 3 3 5-7"/>',assist:'<rect x="4" y="5" width="16" height="14" rx="2"/><path d="M8 9h8M8 13h5"/>',finance:'<path d="M4 20V8h16v12M8 8V4h8v4M3 20h18M9 12h1M14 12h1M9 16h1M14 16h1"/>',language:'<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c3 3 3 15 0 18M12 3c-3 3-3 15 0 18"/>',manage:'<circle cx="9" cy="8" r="3"/><path d="M3 20c1-4 3-6 6-6s5 2 6 6M17 8h5M17 12h5M17 16h5"/>',support:'<path d="M4 13a8 8 0 0 1 16 0"/><path d="M4 13v4a2 2 0 0 0 2 2h2v-6H4M20 13v4a2 2 0 0 1-2 2h-2v-6h4"/>',arch:'<path d="m3 20 9-16 9 16M7 20v-6h10v6M10 14v6M14 14v6"/>',photo:'<rect x="3" y="5" width="18" height="15" rx="2"/><circle cx="12" cy="12" r="3"/><path d="M8 5 9 3h6l1 2"/>',coach:'<path d="M12 3a9 9 0 1 0 9 9"/><path d="m15 3 6 1-1 6M12 12l8-8"/>'};return `<svg viewBox="0 0 24 24" aria-hidden="true">${p[type]}</svg>`};const professions=[['design','Graphic & Web Designers'],['ux','UI/UX Designers'],['social','SMM & Social Media Specialists'],['ai','AI Specialists & AI Content Creators'],['code','Programmers & Developers'],['write','Copywriters & Content Writers'],['video','Video Editors & Motion Designers'],['marketing','Marketing & Digital Marketing'],['search','SEO Specialists'],['data','Business & Data Analysts'],['assist','Virtual Assistants'],['finance','Accountants & Finance Specialists'],['language','Translators & Language Specialists'],['manage','Project & Product Managers'],['support','Customer Support Specialists'],['arch','Architects & 3D Specialists'],['photo','Photographers & Creative Specialists'],['coach','Consultants & Coaches']];
const outcomes=[['Positioning','Կգտնես քո ուժեղ կողմերը, կընտրես ճիշտ ուղղությունը և կհասկանաս՝ ինչ արժեք ես առաջարկում Client-ին։'],['Upwork Profile','Կստեղծես պրոֆիլ, որը հստակ ցույց է տալիս՝ ով ես, ինչ ես առաջարկում և ինչու պետք է Client-ը ընտրի հենց քեզ։'],['Jobs & Proposals','Կսովորես գտնել ճիշտ աշխատանքները, վերլուծել Job Post-ը և գրել Proposal-ներ, որոնք մեծացնում են պատասխան ստանալու հնարավորությունը։'],['Client → Project','Կսովորես ճիշտ հաղորդակցվել Client-ի հետ, բանակցել, պայմանավորվել և պրոֆեսիոնալ կերպով հանձնել Project-ը։'],['Deliver & Get Paid','Կսովորես ճիշտ կազմակերպել աշխատանքը, ժամանակին հանձնել Project-ը և ստեղծել դրական Client experience։'],['Build Your Freelance Career','Կսովորես առաջին Project-ից անցնել repeat clients-ի, բարձրացնել rates-ը և կառուցել կայուն freelance կարիերա։']];
const modules=[['Freelance մտածելակերպ և դիրքավորում',['Freelance vs Employee և freelance շուկայի տրամաբանությունը','Հմտություն vs ծառայություն · պահանջված ուղղություններ','Niche, դիրքավորում և personal brand-ի հիմքեր','Freelance մտածելակերպ՝ կարգապահություն, պատասխանատվություն, մրցակցություն','Գործնական՝ freelancing պատրաստվածության և դիրքավորման checklist']],['Քո Upwork պրոֆիլի կառուցումը',['Ինչ է Upwork-ը՝ Jobs, Proposals, Contracts, Hourly vs Fixed Price','Account-ի ստեղծում, verification, settings և անվտանգ օգտագործում','Profile Photo, Title, Overview, Skills, Portfolio, Hourly Rate','Profile optimization և common mistakes','Competitor analysis · Գործնական՝ պրոֆիլի կառուցում ու audit']],['Ճիշտ աշխատանքների որոնում',['Search, keywords, filters, saved searches և Job Feed','Ինչ Job-երի դիմել՝ budget, client history, competition','Red flags, scam indicators և ինչ Job-երի չդիմել','Upwork algorithm, visibility և Connects','Գործնական՝ իրական Job-ի վերլուծություն']],['Proposal-ներ, որոնք պատասխան են ստանում',['Proposal-ի կառուցվածք՝ bid, cover letter, questions, samples','Client research և անհատականացված proposal','Ինչ հարցեր տալ և ինչպես ավարտել CTA-ով','Follow-up և AI-ի ճիշտ կիրառումը','Գործնական՝ իրական Proposal + հաջողված օրինակների վերլուծություն']],['Client-ից մինչև Project',['Առաջին հաղորդագրություն, discovery և brief','Pricing, negotiation, scope, revisions և deadline','Contract, milestones ու payment protection','Upwork payment systems, difficult clients և boundaries','Գործնական՝ Client Communication Scripts + Project Workflow']],['Կայուն freelance կարիերայի կառուցում',['First client → առաջին 5 clients, review, referral, portfolio update','Discipline, time management և work system','Rates, repeat clients և higher-value services','AI + human skills, specialization և long-term strategy','Արդյունք՝ կայուն freelance կարիերայի գործողությունների համակարգ']]];
const formats=[['🎥','Ձայնագրված դասեր / online','6 շաբաթվա ընթացքում՝ շաբաթական 2 դաս։'],['📚','14+ գործնական դաս','Կոնկրետ թեմաներ՝ Upwork-ից մինչև Client և Project։'],['📝','Գործնական առաջադրանքներ','Յուրաքանչյուր մոդուլում՝ կիրառելի առաջադրանքներ։'],['✅','Առաջադրանքների ստուգում','Կստանաս հետադարձ կապ քո կատարած աշխատանքների վերաբերյալ։'],['💬','Փակ Telegram Chat','Հարցեր կտաս դասընթացի ընթացքում և կստանաս աջակցություն։'],['📂','Նյութերի հասանելիություն','Templates, Checklists, Examples և օգտակար նյութեր։']];const bonuses=[['01','Portfolio Website','Կսովորես ստեղծել քո սեփական Portfolio Website-ը և ձեռք կբերես հմտություն, որը կկիրառես նաև այլ կայքեր ստեղծելու համար։'],['02','Other Freelance Platforms','Upwork-ից բացի կծանոթանաս այլ freelance հարթակների և նոր հնարավորությունների։'],['03','Proposal Vault','Կստանաս պատրաստի Proposal-ների օրինակներ, կառուցվածքներ և մոտեցումներ։'],['04','Freelancer Toolkit','Կստանաս գործնական Checklists, Templates և Scripts՝ Client-ների հետ աշխատանքի փուլերի համար։']];
const faqs=[['Որքա՞ն գումար է անհրաժեշտ Upwork-ը սկսելու համար։','Upwork-ում գրանցվելն ու պրոֆիլ ստեղծելը անվճար է։ Proposal ուղարկելու համար օգտագործվում են Connects․ սկսելու համար խորհուրդ է տրվում ունենալ մոտ 100 Connects, որը մոտ $18 է։ Դասընթացում կսովորես Connects-ը նպատակային օգտագործել։'],['Upwork-ում աշխատելու համար վճարել պե՞տք է։','Հարթակից օգտվելը անվճար է, իսկ աշխատանքի առաջարկներ ուղարկելու համար օգտագործվում են սահմանափակ Connects։ Կսովորես ընտրել ճիշտ Job-երը, վերլուծել Client-ին և չվատնել Connects-ը։'],['Պարտադի՞ր է անգլերենի լավ իմացությունը։','Անգլերենի կատարյալ իմացություն պարտադիր չէ։ Կարևոր է հասկանալ մասնագիտական տեքստերը և պարզ հաղորդակցվել Client-ի հետ։ Աշխատելու ենք նաև Proposal-ների ու հաղորդագրությունների վրա։'],['Դասընթացը սկսնակների՞ համար է։','Այո։ Այն հարմար է և՛ զրոյից սկսողների, և՛ արդեն Upwork պրոֆիլ ունեցող մասնագետների համար, ովքեր չեն ստանում բավարար արձագանքներ կամ client-ներ։'],['Ի՞նչ մասնագիտություն պետք է ունենամ։','Դասընթացը նախատեսված է տարբեր ոլորտների մասնագետների համար՝ դիզայներներ, SMM ու AI մասնագետներ, ծրագրավորողներ, copywriter-ներ, հաշվապահներ, մարքեթոլոգներ և այլ հեռավար ծառայություն մատուցողներ։'],['Պարտադի՞ր է ունենալ Upwork-ի փորձ։','Ոչ։ Կարող ես սկսել զրոյից․ դասընթացը քայլ առ քայլ ցույց է տալիս ճանապարհը՝ պրոֆիլից մինչև Client-ի հետ համագործակցություն։'],['Ինչպե՞ս եմ ստանալու դասերը։','Բոլոր դասերը ձայնագրված են և հասանելի կլինեն Telegram-ում։ Ծրագիրը նախատեսված է 6 շաբաթվա ընթացքում՝ շաբաթական 2 դասի ռիթմով։'],['Արդյո՞ք առաջադրանքները ստուգվելու են։','Այո։ Կատարած առաջադրանքները կստուգվեն, և կստանաս հետադարձ կապ։'],['Կարո՞ղ եմ հարցեր տալ դասընթացի ընթացքում։','Այո։ Մասնակիցների համար կլինի փակ Telegram Chat, որտեղ կարող ես հարցեր ուղղել ու ստանալ աջակցություն։'],['Ի՞նչ արդյունք կարող եմ ակնկալել։','Կունենաս գործնական համակարգ՝ ճիշտ ներկայանալու, համապատասխան Job-եր գտնելու, նպատակային Proposal-ներ գրելու և Client-ների հետ վստահ աշխատելու համար։ Արդյունքը կախված է նաև քո փորձից, ակտիվությունից ու կիրառած քայլերից։']];
const mount=(id,data,fn)=>document.querySelector(id).innerHTML=data.map(fn).join('');mount('#professionGrid',professions,x=>`<article class="profession"><i>${icon(x[0])}</i><span>${x[1]}</span></article>`);mount('#outcomeList',outcomes,(x,i)=>`<article><b>0${i+1}</b><div><h3>${x[0]}</h3><p>${x[1]}</p></div><span>↗</span></article>`);mount('#moduleList',modules,(x,i)=>`<details><summary><b>ՄՈԴՈՒԼ ${i+1}</b><h3>${x[0]}</h3><span>+</span></summary><ul>${x[1].map(t=>`<li>${t}</li>`).join('')}</ul></details>`);mount('#formatGrid',formats,x=>`<article><i>${x[0]}</i><h3>${x[1]}</h3><p>${x[2]}</p></article>`);mount('#bonusGrid',bonuses,x=>`<article><b>${x[0]}</b><h3>${x[1]}</h3><p>${x[2]}</p></article>`);mount('#faqList',faqs,x=>`<details><summary>${x[0]} <b>+</b></summary><p>${x[1]}</p></details>`);document.querySelector('#instructorText').innerHTML=`<p>Ես Նարգիզն եմ՝ <b>Graphic & Brand Designer, AI Designer, Freelancer և դասընթացավար</b>։</p><p>Իմ freelance ճանապարհը սկսել եմ <b>2020 թվականին՝ Upwork-ում ստանալով ընդամենը $5 արժողությամբ առաջին պատվերս</b>։ Հետո եկավ <b>$1,200 արժողությամբ նախագիծ՝ քարտերի դիզայն</b>։ Այդ փորձը ցույց տվեց, որ freelance-ը կարող է լինել ոչ միայն եկամտի աղբյուր, այլև ազատություն՝ աշխատելու քո հմտություններով և ստեղծելու նոր հնարավորություններ։</p><p>Դիզայնի ոլորտում աշխատում եմ 7 տարի, իսկ վերջին 5 տարիների ընթացքում նաև դասավանդում եմ։ Դասավանդել եմ <b>Picsart</b> և <b>AITC</b> ընկերություններում։ 2022-ին համահիմնել եմ Artuyt Design Agency & School-ը, որտեղ աշխատում ենք իրական Client նախագծերի և կրթական ծրագրերի վրա։</p><p>Այս դասընթացում կիսվելու եմ ոչ միայն տարիների ընթացքում ձեռք բերած գիտելիքով, այլ նաև ներկայիս freelance աշխատանքի, Client-ների հաղորդակցության, համագործակցությունների և իրական նախագծերի փորձով։</p><blockquote>Լավ մասնագետ դառնալու համար միայն մասնագիտական հմտությունը բավարար չէ։ Պետք է կարողանալ ճիշտ ներկայացնել քո արժեքը, գտնել համապատասխան Client-ներ, կառուցել վստահություն և հնարավորությունը վերածել երկարաժամկետ համագործակցության։</blockquote>`;
const revealTargets=document.querySelectorAll('.section-head,.audience-copy,.profession,.outcome-list article,.module-list details,.format-grid article,.bonus-grid article,.instructor-photo,.instructor-copy,.enrollment>div,.faq-list details');revealTargets.forEach((el,i)=>{el.classList.add('reveal');el.style.setProperty('--delay',`${(i%6)*65}ms`)});const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');revealObserver.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -35px'});revealTargets.forEach(el=>revealObserver.observe(el));document.querySelectorAll('.profession,.format-grid article,.bonus-grid article').forEach(card=>{card.addEventListener('pointermove',e=>{if(matchMedia('(pointer:fine)').matches){const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`translateY(-7px) rotateX(${-y*3}deg) rotateY(${x*3}deg)`}});card.addEventListener('pointerleave',()=>card.style.transform='')});
const heroArt=document.querySelector('.hero-art');heroArt.addEventListener('pointermove',e=>{if(matchMedia('(pointer:fine)').matches){const r=heroArt.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;heroArt.style.setProperty('--mx',`${x*23}px`);heroArt.style.setProperty('--my',`${y*16}px`);heroArt.style.setProperty('--scale','1.11')}});heroArt.addEventListener('pointerleave',()=>{heroArt.style.setProperty('--mx','0px');heroArt.style.setProperty('--my','0px');heroArt.style.setProperty('--scale','1.035')});
const heroImage=document.createElement('img');heroImage.className='hero-image';heroImage.src='assets/hero-cloud-character.jpg';heroImage.alt='Artuyt Design Academy character in the clouds';heroArt.replaceChildren(heroImage);

const bonusIcons=['⌘','◎','✦','↗'];document.querySelectorAll('#bonusGrid article').forEach((card,index)=>{const number=card.querySelector('b');if(number){number.innerHTML=`<i class="bonus-icon" aria-hidden="true">${bonusIcons[index]}</i><span>${number.textContent}</span>`}});

const enrollmentInfo=['Ձայնագրված դասեր / online','Գործնական առաջադրանքներ','14+ գործնական դաս','Առաջադրանքների ստուգում','Փակ Telegram Chat','Նյութերի հասանելիություն','4 բոնուս'];document.querySelector('#enroll > div:first-child').insertAdjacentHTML('beforeend',`<ul class="enrollment-list">${enrollmentInfo.map(item=>`<li><span>✦</span>${item}</li>`).join('')}</ul>`);

document.querySelector('.bonuses .section-head h2').textContent='ԲՈՆՈՒՍՆԵՐ';
const professionGroups=[['Դիզայն և ստեղծարարություն',professions.slice(0,4).concat(professions.slice(6,7),professions.slice(15,18))],['Թվային և տեխնոլոգիական մասնագիտություններ',professions.slice(4,6).concat(professions.slice(7,10))],['Բիզնես և հեռավար ծառայություններ',professions.slice(10,15)]];document.querySelector('#professionGrid').innerHTML=professionGroups.map(([title,items])=>`<article class="profession-group"><h3>${title}</h3><div>${items.map(item=>`<p><i>${icon(item[0])}</i><span>${item[1]}</span></p>`).join('')}</div></article>`).join('');
const formatIconTypes=['video','data','write','assist','support','photo'];document.querySelector('#formatGrid').innerHTML=formats.map((item,index)=>`<article><i>${icon(formatIconTypes[index])}</i><h3>${item[1]}</h3><p>${item[2]}</p></article>`).join('');
const refinements=document.createElement('link');refinements.rel='stylesheet';refinements.href='refinements.css';document.head.append(refinements);

document.querySelector('.hero-copy .button').insertAdjacentHTML('afterend','<p class="hero-system">6 մոդուլ՝ մեկ ամբողջական <em>freelance համակարգ</em></p>');
document.querySelector('.gradient-cta > p').remove();
document.querySelector('.gradient-cta strong').insertAdjacentHTML('afterend','<div class="countdown" aria-label="Նախավաճառքի ավարտի հետհաշվարկ"><span>ՆԱԽԱՎԱՃԱՌՔԻ ԱՎԱՐՏԻՆ</span><div><b data-count="days">00</b><i>օր</i><b data-count="hours">00</b><i>ժ</i><b data-count="minutes">00</b><i>ր</i></div></div>');
const deadline=()=>{const now=new Date(),year=now.getFullYear();let date=new Date(year,8,1,23,59,59);if(now>date)date=new Date(year+1,8,1,23,59,59);return date};const updateCountdown=()=>{let seconds=Math.max(0,Math.floor((deadline()-new Date())/1000));const parts={days:Math.floor(seconds/86400),hours:Math.floor(seconds%86400/3600),minutes:Math.floor(seconds%3600/60)};Object.entries(parts).forEach(([unit,value])=>document.querySelector(`[data-count="${unit}"]`).textContent=String(value).padStart(2,'0'))};updateCountdown();setInterval(updateCountdown,60000);

document.querySelector('.hero-system').remove();
document.querySelector('.outcomes .section-head h2').innerHTML='Սկսիր քո<br><em>ֆրիլանս կարիերան</em>';
document.querySelector('#program .section-head h2').innerHTML='6 մոդուլ՝ մեկ ամբողջական<br><em>freelance համակարգ</em>';
document.querySelectorAll('a[target="_blank"]').forEach(link=>link.rel='noopener noreferrer');
document.querySelector('.hero-copy .eyebrow').remove();
document.querySelector('footer').insertAdjacentHTML('beforeend','<div class="footer-contact"><a href="tel:+3749988433">+374 99 884 33</a><a href="mailto:artuytdesign@gmail.com">artuytdesign@gmail.com</a><a href="https://www.instagram.com/artuytdesignagency/" target="_blank" rel="noopener noreferrer">@artuytdesignagency ↗</a><a href="https://www.instagram.com/artuytdesign/" target="_blank" rel="noopener noreferrer">@artuytdesign ↗</a></div>');

/* Registration always opens the course bot. */
const telegramBotUrl='https://t.me/upwork_freelancer_arm_bot';
document.querySelectorAll('.button').forEach(button=>{
  if(/գրանց/i.test(button.textContent)){
    button.href=telegramBotUrl;
    button.target='_blank';
    button.rel='noopener noreferrer';
  }
});
const telegramCta=document.querySelector('.gradient-cta .button');
telegramCta.href=telegramBotUrl;
telegramCta.target='_blank';
telegramCta.rel='noopener noreferrer';
telegramCta.innerHTML='Գրանցվել դասընթացին <b>↗</b>';
